export { default as MovieList } from './Movie/List'
export { default as MovieDetail } from './Movie/Detail'
export { default as MovieAdd } from './Movie/Add'
export { default as MovieUpdate } from './Movie/Update'
export { default as TicketingList } from './Ticketing/List'
export { default as TicketingDetail } from './Ticketing/Detail'
export { default as Login } from './Login'
export { default as Home } from './Home'